# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.box = "ubuntu/trusty64"
    config.vm.synced_folder "../", "/vagrant"
    config.vm.synced_folder "../../django-popolo/", "/django-popolo"
    config.vm.hostname = "opdev"
    config.vm.network :private_network, ip: "192.168.111.104"
    config.vm.network "forwarded_port", guest: 8004, host: 8004
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
    config.vm.network :forwarded_port, guest: 22, host: 2204

    # box settings
    config.vm.provider :virtualbox do |vb|
        vb.name = "vagrant_api"
        vb.customize ["modifyvm", :id, "--memory", 2048]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    # provisioning
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end
end
